#version 430 core
layout(local_size_x = 32, local_size_y = 32) in;
layout(rgba32f, binding = 0) readonly uniform image2D img_in;
layout(rgba32f, binding = 1) writeonly uniform image2D img_out;

uniform float Strength; // 0.05 = 5% 확률로 노이즈

// 간단한 랜덤 함수
float rand(vec2 co){
    return fract(sin(dot(co, vec2(12.9898, 78.233))) * 43758.5453);
}

void main() {
    ivec2 pos = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(img_in);
    if (pos.x >= size.x || pos.y >= size.y) return;

    vec4 color = imageLoad(img_in, pos);
    float r = rand(vec2(pos) * Strength); // 시드에 Strength를 섞어서 매번 다르게

    if (r < Strength * 0.5) color = vec4(0,0,0,1); // Pepper (Black)
    else if (r < Strength)  color = vec4(1,1,1,1); // Salt (White)

    imageStore(img_out, pos, color);
}